### PR TITLE
Bump to juno baseApp

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
ffmpeg fails to build :/ Will take a look a bit later

**Comment by bilelmoussaoui** [comment]
@nedrichards The builds fail because the new freedesktop runtime doesn't include `chrpath` anymore. Should I add it to the sources here? Not sure if it's possible to build ffmpeg without it.

**Comment by TingPing** [comment]
My apps build ffmpeg fine, but this has been brought up before so we should get `chrpath` in the sdk again.

**Comment by nedrichards** [comment]
without chrpath bad things can happen to your transcoding, so absolutely yes

**Comment by bilelmoussaoui** [comment]
Waiting for this to get fixed https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/417

**Comment by TingPing** [comment]
Maybe just updating ffmpeg to 4.0 (which you should anyway) will solve it, since that is what I build w/o issue.

**Comment by bilelmoussaoui** [comment]
Let me check that! Thanks for the hint

**Comment by bilelmoussaoui** [comment]
Updated ffmpeg & imagemagick

**Comment by nedrichards** [comment]
@bilelmoussaoui I may need to be more clear. Without chrpath the entire point of this app is undermined and doesn't work since apps use ffmpeg from the html5 extension that doesn't have codecs rather than the version inside the app that does. Please don't merge anything that removes that.

**Comment by nedrichards** [comment]
@bilelmoussaoui I tested this manually and it just doesn't seem to work for me for the codecs it's supposed to without rpath. As such I've copied the best bits from here into a different PR for now until they add it to the SDK.

**Comment by bilelmoussaoui** [comment]
@nedrichards So this one can be closed? Otherwise, we can add rpath and remove it once it's on the SDK. This way we won't have to keep 1.6 stuff alive and have an up to date application here on flathub.

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
I'm going to try a new PR for this and fix the OARS as well. Closing for now.

**Comment by nedrichards** [comment]
OK, still doesn't work with 18.08 and the obvious things to try. I've fixed the OARS issue though and pushed that.

**Pull request closed without merging**
